name: 02-Develop
on:
  push:
    branches:
      - develop

permissions:
  pull-requests: write
  id-token: write
  contents: write

jobs:
  ec2-deployment:
    uses: ./.github/workflows/ec2-deployment.yml
    with:
      environment: dev
      create_release: true